# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_choosed', models.DateTimeField(null=True)),
                ('date_voluntary', models.DateTimeField(null=True)),
                ('date_removed', models.DateTimeField(null=True)),
                ('justification', models.TextField(null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_rotation.Cycle')),
                ('removed_by', models.ForeignKey(db_column='removed_by_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FK_REMOVED_BY', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='FK_USER', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
